restaurant/food/urls.py
from . import views
from django.urls import path

app_name = "food"
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("<int:pk>/", views.Detail.as_view(), name="detail"),
    path("add", views.CreateItem.as_view(), name="create_item"),
    path("update/<int:id>", views.update_item, name="update_item"),
    path("delete/<int:id>", views.delete_item, name="delete_item"),
]

restaurant/restaurant/urls.py
from django.contrib import admin
from django.contrib.auth import views as authentication_views
from django.urls import include, path
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("food/", include("food.urls")),
    path("register/", user_views.register, name="register"),
    path(
        "login/",
        authentication_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        authentication_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path("profile/", user_views.profilepage, name="profile"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Item(models.Model):
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="place_holder.png")
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

restaurant/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="profilepic.jpg", upload_to="profile_pictures")
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

restaurant/food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["item_name", "item_desc", "item_price", "item_image"]

restaurant/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

restaurant/food/views.py
from django.shortcuts import render, redirect
from .models import Item
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


class Index(ListView):
    template_name = "food/index.html"
    context_object_name = "item_list"
    paginate_by = 2

    def get_queryset(self):
        food_name = self.request.GET.get("food_name")
        if food_name and food_name != "":
            return Item.objects.filter(item_name__icontains=food_name)
        else:
            return Item.objects.all()


class Detail(DetailView):
    model = Item
    template_name = "food/detail.html"


class CreateItem(CreateView):
    model = Item
    fields = ["item_name", "item_desc", "item_price", "item_image"]
    template_name = "food/item-form.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect("food:index")
    return render(request, "food/item-form.html", {"form": form, "item": item})


def delete_item(request, id):
    item = Item.objects.get(id=id)
    if request.method == "POST":
        item.delete()
        return redirect("food:index")
    return render(request, "food/item-delete.html", {"item": item})

restaurant/users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.contrib import messages
from .forms import RegisterForm


# Create your views here.
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            messages.success(request, f"Welcome {username}, your account is created.")
            form.save()
            return redirect("login")
    else:
        form = RegisterForm()
    return render(request, "users/register.html", {"form": form})


@login_required
def profilepage(request):
    return render(request, "users/profile.html")

restaurant/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'food/style.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-light">
        <a href="#" class="navbar-brand">Food App</a>
          <div>
            <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'food:create_item' %}">Add Item</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Delete Item</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">View Item</a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                    {% endif %}
                </li>
            </ul>
          </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class ="alert alert-{{ message.tags }}">
                {{ message }} - {{ message.tags }}
            </div>
        {% endfor %}
    {% endif %}
  {% block body %}
  {% endblock %}
</body>
</html>

restaurant/food/templates/food/detail.html
{% extends 'food/base.html' %}
{% load static %}
{% block body %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img src="{% static 'food/img/' %}{{ object.item_image }}" height="150px">
            </div>
            <div class="col-md-4">
                <h3>{{ object.item_name }}</h3>
                <h5>{{ object.item_desc }}</h5>
                <h6>{{ object.item_price }}</h6>
                {{ object.item_image }}
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:delete_item' item.id %}" class="btn btn-success">Delete</a>
            </div>
        </div>
{% endblock %}

restaurant/food/templates/food/index.html
{% extends 'food/base.html' %}
{% load static %}
{% block body %}
    <form action="" method="GET">
        <input type="search" name="food_name">
        <button type="submit">Search</button>
    </form>
    {% for item in item_list%}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img src="{% static 'food/img/' %}{{ item.item_image }}" height="150px" width="250px" vspace="2px">
            </div>
            <div class="col-md-4">
                <h3>{{ item.id }} </h3>
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_desc }}</h5>
                <h6>{{ item.item_price }}</h6>
                {{ item.item_image }}
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id  %}" class="btn bnt-success">Details</a>
                <a href="{% url 'food:update_item' item.id %}" class="btn btn-success">Edit</a>
            </div>
        </div>
    {% endfor %}
    <div class="pagination offset-md-2" >
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

restaurant/food/templates/food/item-delete.html
<form method="POST">
  {% csrf_token %}
  <h2>Are you sure you want to delete {{ item.item_name }}</h2>
  <button type="submit">Confirm</button>
</form>

restaurant/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <div class="card">
          <div class="card-header text-white bg-info">
            <div class="card-title">
              Add Item
            </div>
          </div>
          <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              {{ form }}
              <div class="btn-info"> <button type="submit">Add Item </button></div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

restaurant/users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <div class="card">
          <div class="card-header text-white bg-info">
            <div class="card-title">
              Login
            </div>
          </div>
          <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group">
                  {{ field.name }}
                  {{ field }}
                </div>
              {% endfor %}
              <div class="btn-info"> <button type="submit">Login </button></div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

restaurant/users/templates/users/logout.html
<h1>
  You have been logged out.
</h1>

restaurant/users/templates/users/profile.html
<h1> {{ user.username }}</h1>
<img src ="{{ user.profile.image.url }}">

restaurant/users/templates/users/register.html
{% extends 'food/base.html' %}
{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <div class="card">
          <div class="card-header text-white bg-info">
            <div class="card-title">
              Register
            </div>
          </div>
          <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group">
                  {{ field.name }}
                  <br>
                  {{ field }}
                </div>
              {% endfor %}
              <div class="btn-info"> <button type="submit">Login </button></div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}